CREATE TABLE IF NOT EXISTS series (id INTEGER PRIMARY KEY, title TEXT NOT NULL, year INTEGER, path TEXT NOT NULL, poster TEXT);
CREATE TABLE IF NOT EXISTS episodes (id INTEGER PRIMARY KEY, series_id INTEGER NOT NULL, season INTEGER NOT NULL, number INTEGER NOT NULL, title TEXT NOT NULL, file_path TEXT);
CREATE TABLE IF NOT EXISTS operations (id TEXT PRIMARY KEY, episode_id INTEGER NOT NULL, source TEXT NOT NULL, mode TEXT NOT NULL, destination TEXT NOT NULL, status TEXT NOT NULL, message TEXT NOT NULL);
