// Owned temporary API/worker + browser. Response overlays below test UI rendering, not detector truth.
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE||'/usr/lib/node_modules/playwright/index.mjs').href);
const origin=process.env.UI_URL,remote=process.env.UI_PROVIDER_ORIGIN;
assert.equal(new URL(origin).hostname,'127.0.0.1');assert.equal(new URL(remote).hostname,'127.0.0.1');
const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_EXECUTABLE?{executablePath:process.env.PLAYWRIGHT_EXECUTABLE}:{})}),page=await browser.newPage();page.setDefaultTimeout(20000);
const errors=[],posts=[],held=[];page.on('pageerror',error=>errors.push(error.message));page.on('request',request=>{if(request.method()!=='GET')posts.push(request.url());});
let acceptDialogs=true;page.on('dialog',dialog=>acceptDialogs?dialog.accept():dialog.dismiss());
const nav=page.getByRole('navigation',{name:'Workspace'}),health=page.getByRole('region',{name:'Health',exact:true}),activity=page.getByRole('region',{name:'Activity',exact:true}),master=page.getByRole('region',{name:'Completed-download handling',exact:true});
const until=async(fn,accept,label)=>{const end=Date.now()+25000;while(Date.now()<end){const result=await fn();if(accept(result))return result;await page.waitForTimeout(100);}assert.fail(label);};
const get=async path=>{const response=await page.request.get(origin+path);assert.equal(response.status(),200,await response.text());return response.json();};
const idle=region=>until(()=>region.getAttribute('aria-busy'),value=>value==='false','Panel did not finish readback');
const refresh=async()=>{await idle(health);await health.getByRole('button',{name:'Refresh health',exact:true}).click();await idle(health);};
const openHealth=async()=>{await nav.getByRole('button',{name:'Health',exact:true}).click();await idle(health);};
const run=async scope=>{await health.getByLabel('Health scope').selectOption(scope);await idle(health);const reply=page.waitForResponse(response=>new URL(response.url()).pathname==='/api/v1/health/commands'&&response.request().method()==='POST');await health.getByRole('button',{name:`Run ${scope} health checks`,exact:true}).click();const response=await reply;assert.equal(response.status(),202);return response.json();};
// Migration46 adds removed metadata; include previously registered root checks too.
const identities=['movies','tv'].flatMap(domain=>['completed_download_handling','download_client_communication','download_client_root_folder','removed_metadata'].map(key=>`${domain}:${key}`));
const identity=check=>`${check.identity.scope}:${check.identity.check_key}`;
const issueFor=(snapshot,domain,key)=>snapshot.issues.find(issue=>identity(issue)===`${domain}:${key}`);
const current=async()=>{const snapshot=await until(()=>get('/api/v1/health'),snapshot=>snapshot.summary.current===8&&!snapshot.active_command,'All eight scoped checks did not become current');assert.equal(snapshot.summary.total,8);assert.deepEqual(snapshot.checks.map(identity).sort(),identities);assert.deepEqual(snapshot.coverage.identities.map(value=>`${value.scope}:${value.check_key}`).sort(),identities);for(const check of snapshot.checks){assert.equal(check.evaluation,'current');assert.equal(check.last_error,null);}return snapshot;};
const communicationRow=domain=>health.getByRole('article',{name:`${domain}:download_client_communication`,exact:true});
const settings=async domain=>{await health.getByLabel('Health scope').selectOption('all');await idle(health);await health.getByRole('button',{name:`Open ${domain} completed-download settings`,exact:true}).click();await activity.getByText(`Opened ${domain} completed-download settings.`,{exact:true}).waitFor();await idle(activity);assert.equal(await master.getByLabel('Completed-download media').inputValue(),domain);};
const save=async enabled=>{await idle(activity);await master.getByLabel('Enable completed-download handling',{exact:true}).setChecked(enabled);await master.getByRole('button',{name:'Save completed-download handling',exact:true}).click();await activity.getByText('Completed-download domain setting saved.',{exact:true}).waitFor();await idle(activity);};
const dismiss=async()=>{const buttons=health.getByRole('button',{name:/Dismiss request .* tracking/});const count=await buttons.count();assert.ok(count<=8);for(let n=0;n<count;n++)await buttons.first().click();assert.equal(await buttons.count(),0);};
try{
 await page.goto(origin);await openHealth();let fresh=await current();assert.equal(fresh.issues.some(issue=>issue.identity.scope==='tv'&&issue.reason.startsWith('cdh_undefined')),true);assert.equal(issueFor(fresh,'movies','completed_download_handling'),undefined);await health.getByLabel('Health scope').selectOption('all');await idle(health);await refresh();
 for(const domain of ['tv','movies']){
  const warning=issueFor(fresh,domain,'download_client_communication');assert.equal(warning.reason,'download_client_none_available');assert.equal(warning.severity,'warning');assert.equal(warning.compatibility_type,'DownloadClientCheck');
  await communicationRow(domain).getByText(`warning: ${warning.message} (${warning.reason})`,{exact:true}).waitFor();assert.equal(await communicationRow(domain).getByRole('link',{name:'Check help'}).getAttribute('href'),`https://wiki.servarr.com/${domain==='tv'?'sonarr':'radarr'}/system#no-download-client-is-available`);
 }
 await run('all');await current();await refresh();await health.getByText('Requested generations observed in the current epoch.',{exact:true}).waitFor();
 // First lazy Activity mount, both domains, equal-true explicit save and observed issue/restore.
 for(const domain of ['movies','tv']){
  const before=posts.length;await settings(domain);assert.equal(posts.length,before,'Navigation must not mutate settings');
  assert.equal((await get(`/api/v1/${domain}/completed-download-handling`)).defined,false);
  await save(true);assert.equal((await get(`/api/v1/${domain}/completed-download-handling`)).defined,true);
  await openHealth();await run(domain);await current();await refresh();assert.equal(issueFor(await get('/api/v1/health'),domain,'completed_download_handling'),undefined);
  await settings(domain);await save(false);await openHealth();await run(domain);await current();await refresh();assert.equal((await get('/api/v1/health')).issues.some(issue=>issue.identity.scope===domain&&issue.reason==='cdh_disabled'),true);
  await settings(domain);await save(true);await openHealth();await run(domain);await current();await refresh();await dismiss();
 }
 // Dirty refusal retains domain and draft; explicit acceptance reaches requested domain.
 await settings('tv');await master.getByLabel('Enable completed-download handling',{exact:true}).uncheck();await openHealth();acceptDialogs=false;
 await health.getByRole('button',{name:'Open movies completed-download settings',exact:true}).click();await activity.getByText('Settings navigation declined; previous domain and drafts retained.',{exact:true}).waitFor();assert.equal(await master.getByLabel('Completed-download media').inputValue(),'tv');assert.equal(await master.getByLabel('Enable completed-download handling',{exact:true}).isChecked(),false);
 acceptDialogs=true;await openHealth();await settings('movies');assert.equal(await master.getByLabel('Enable completed-download handling',{exact:true}).isChecked(),true);
 // Delay an Activity read; an external request must wait, not disappear.
 let releaseRead,readStarted;const gate=new Promise(resolve=>releaseRead=resolve),started=new Promise(resolve=>readStarted=resolve);held.push(releaseRead);let holdRead=true;
 await page.route('**/api/v1/commands?*',async route=>{if(!holdRead)return route.continue();holdRead=false;const response=await route.fetch();readStarted();await gate;await route.fulfill({response});});
 await activity.getByRole('button',{name:'Reload activity',exact:true}).click();await Promise.race([started,new Promise((_,reject)=>setTimeout(()=>reject(new Error('Activity gate not entered')),20000))]);await openHealth();await health.getByRole('button',{name:'Open tv completed-download settings',exact:true}).click();await activity.getByText('Waiting to open tv completed-download settings until current work finishes.',{exact:true}).waitFor();releaseRead();await activity.getByText('Opened tv completed-download settings.',{exact:true}).waitFor();await idle(activity);await page.unroute('**/api/v1/commands?*');
 // Unknown settings write blocks Health navigation until explicit Activity readback.
 const masterPattern='**/api/v1/tv/completed-download-handling';await page.route(masterPattern,async route=>{if(route.request().method()!=='PUT')return route.continue();assert.equal((await route.fetch()).status(),200);await route.abort('failed');});
 await master.getByLabel('Enable completed-download handling',{exact:true}).uncheck();await master.getByRole('button',{name:'Save completed-download handling',exact:true}).click();await activity.getByRole('alert').filter({hasText:'The request may have committed. Related writes'}).waitFor();await page.unroute(masterPattern);await openHealth();await health.getByRole('button',{name:'Open movies completed-download settings',exact:true}).click();await activity.getByText('Settings navigation refused: resolve the unknown write outcome, then request navigation again.',{exact:true}).waitFor();assert.equal(await master.getByLabel('Completed-download media').inputValue(),'tv');await activity.getByRole('button',{name:'Reload activity',exact:true}).click();await idle(activity);await save(true);await openHealth();await current();
 // One owned shared client, with distinct TV/movie categories.
 const scope=category=>({category,imported_category:null,recent_priority:0,older_priority:0});
 const created=await page.request.post(origin+'/api/v1/providers',{data:{name:'Health browser client',enabled:true,priority:1,settings:{implementation:'qbittorrent',endpoint:remote,tv:scope('tv'),movies:scope('movies')},credentials:{kind:'username_password',username:'fixture-user',password:'fixture-good'}}});assert.equal(created.status(),201,await created.text());await current();
 const provider=await created.json();
 // Real category-scoped item probes restore both no-client warnings; this is not an overlay.
 await run('all');let healthy=await current();await refresh();await dismiss();
 for(const domain of ['tv','movies']){assert.equal(issueFor(healthy,domain,'download_client_communication'),undefined);await communicationRow(domain).getByRole('heading',{name:`${domain}:download_client_communication — current`,exact:true}).waitFor();await communicationRow(domain).getByText('No cached issue on this check; evaluation state determines freshness.',{exact:true}).waitFor();}
 // Mode1 returns503 only from the actual item-list endpoint, after successful auth/version.
 // CDH uses client_status (preferences/categories), not test_connection or item-list probing.
 // Item-only503 therefore leaves both CDH checks current/healthy and communication current/Error.
 assert.equal((await page.request.post(remote+'/fixture-mode?mode=1')).status(),204);await run('all');
 const failed=await until(()=>get('/api/v1/health'),snapshot=>!snapshot.active_command&&['tv','movies'].every(domain=>issueFor(snapshot,domain,'download_client_communication')?.reason==='download_client_communication_failed'),'Both scoped item-list failures were not published');
 assert.equal(failed.summary.total,8);assert.deepEqual(failed.checks.map(identity).sort(),identities);for(const domain of ['tv','movies']){assert.equal(failed.checks.find(check=>identity(check)===`${domain}:completed_download_handling`).evaluation,'current');assert.equal(issueFor(failed,domain,'completed_download_handling'),undefined);}assert.equal(failed.summary.current,8);assert.equal(failed.summary.failed,0);assert.equal(failed.summary.non_ok,2);
 for(const domain of ['tv','movies']){
  const issue=issueFor(failed,domain,'download_client_communication');assert.equal(issue.severity,'error');assert.equal(issue.compatibility_type,'DownloadClientCheck');assert.equal(failed.checks.find(check=>identity(check)===`${domain}:download_client_communication`).evaluation,'current');
  assert.equal(issue.message,`Unable to retrieve items from download client Health browser client (${provider.id}). Review its connection, authentication and protocol settings.`);assert.equal(issue.message.includes('PRIVATE_FIXTURE'),false);assert.equal(issue.message.includes(remote),false);
  await health.getByLabel('Health scope').selectOption(domain);await idle(health);await refresh();
  const scoped=await get(`/api/v1/health?scope=${domain}`);assert.equal(scoped.summary.total,4);assert.deepEqual(scoped.checks.map(identity).sort(),identities.filter(value=>value.startsWith(`${domain}:`)));
  await communicationRow(domain).getByText(`error: ${issue.message} (${issue.reason})`,{exact:true}).waitFor();assert.equal(await communicationRow(domain).getByRole('link',{name:'Check help'}).getAttribute('href'),`https://wiki.servarr.com/${domain==='tv'?'sonarr':'radarr'}/system#unable-to-communicate-with-download-client`);assert.equal(await communicationRow(domain==='tv'?'movies':'tv').count(),0);
 }
 assert.equal((await page.request.post(remote+'/fixture-mode?mode=0')).status(),204);await run('all');healthy=await current();await refresh();await dismiss();
 for(const domain of ['tv','movies']){assert.equal(issueFor(healthy,domain,'download_client_communication'),undefined);await communicationRow(domain).getByRole('heading',{name:`${domain}:download_client_communication — current`,exact:true}).waitFor();await communicationRow(domain).getByText('No cached issue on this check; evaluation state determines freshness.',{exact:true}).waitFor();}
 console.log('PASS actual API: four scoped registry identities; TV/movie communication Warning→healthy→named-client Error→healthy; scoped help links; item-only failure leaves both CDH checks current/healthy');
 // Shared provider write and child policy write cannot be bypassed by Health navigation.
 await nav.getByRole('button',{name:'Providers',exact:true}).click();await page.getByRole('button').filter({hasText:'Health browser client'}).click();await page.getByLabel('Name',{exact:true}).fill('Health browser client edited');
 let releaseProvider,providerStarted;const providerGate=new Promise(resolve=>releaseProvider=resolve),providerBegun=new Promise(resolve=>providerStarted=resolve);held.push(releaseProvider);
 const providerPattern=`**/api/v1/providers/${provider.id}`;
 await page.route(providerPattern,async route=>{if(route.request().method()!=='PUT')return route.continue();const response=await route.fetch();assert.equal(response.status(),200);providerStarted();await providerGate;await route.fulfill({response});});
 await page.getByRole('button',{name:'Save provider',exact:true}).click();await Promise.race([providerBegun,new Promise((_,reject)=>setTimeout(()=>reject(new Error('Provider gate not entered')),20000))]);await openHealth();await health.getByLabel('Health scope').selectOption('all');await idle(health);await health.getByRole('button',{name:'Open movies completed-download settings',exact:true}).click();await activity.getByText('Waiting to open movies completed-download settings until current work finishes.',{exact:true}).waitFor();releaseProvider();await activity.getByText('Opened movies completed-download settings.',{exact:true}).waitFor();await idle(activity);await page.unroute(providerPattern);
 await activity.getByLabel('Download client').selectOption(provider.id);await idle(activity);
 const child=page.getByRole('region',{name:'Completed downloads',exact:true});
 let releaseChild,childStarted;const childGate=new Promise(resolve=>releaseChild=resolve),childBegun=new Promise(resolve=>childStarted=resolve);held.push(releaseChild);const policyPattern=`**/api/v1/download-processing/policies/${provider.id}/movies`;
 await page.route(policyPattern,async route=>{if(route.request().method()!=='PUT')return route.continue();const response=await route.fetch();assert.equal(response.status(),200);childStarted();await childGate;await route.fulfill({response});});
 await child.getByLabel('Completed-download imports',{exact:true}).selectOption('off');await child.getByRole('button',{name:'Save import policy',exact:true}).click();await Promise.race([childBegun,new Promise((_,reject)=>setTimeout(()=>reject(new Error('Child gate not entered')),20000))]);await openHealth();await health.getByRole('button',{name:'Open tv completed-download settings',exact:true}).click();await activity.getByText('Waiting to open tv completed-download settings until current work finishes.',{exact:true}).waitFor();await until(async()=>await activity.getByText('Reading activity…',{exact:true}).count()===0&&await child.getByText('Reading processing status…',{exact:true}).count()===0,Boolean,'Resumed settings/status reads did not finish');releaseChild();await activity.getByText('Opened tv completed-download settings.',{exact:true}).waitFor();await idle(activity);await page.unroute(policyPattern);await openHealth();await current();
 // Force an accepted child write to race a resumed parent read: uncertainty must refuse navigation,
 // retain the old domain, and require explicit readback plus a new navigation request.
 await settings('tv');await idle(activity);
 let releaseRaceWrite,raceWriteStarted,releaseRaceRead,raceReadStarted;
 const raceWriteGate=new Promise(resolve=>releaseRaceWrite=resolve),raceWriteBegun=new Promise(resolve=>raceWriteStarted=resolve),raceReadGate=new Promise(resolve=>releaseRaceRead=resolve),raceReadBegun=new Promise(resolve=>raceReadStarted=resolve);held.push(releaseRaceWrite,releaseRaceRead);
 const racePolicy=`**/api/v1/download-processing/policies/${provider.id}/tv`;let holdResume=false;
 await page.route(racePolicy,async route=>{if(route.request().method()!=='PUT')return route.continue();const response=await route.fetch();assert.equal(response.status(),200);raceWriteStarted();await raceWriteGate;await route.fulfill({response});});
 await page.route('**/api/v1/commands?*',async route=>{if(!holdResume)return route.continue();holdResume=false;const response=await route.fetch();raceReadStarted();await raceReadGate;await route.fulfill({response});});
 await child.getByLabel('Completed-download imports',{exact:true}).selectOption('off');await child.getByRole('button',{name:'Save import policy',exact:true}).click();await Promise.race([raceWriteBegun,new Promise((_,reject)=>setTimeout(()=>reject(new Error('Race write gate not entered')),20000))]);await openHealth();holdResume=true;await health.getByRole('button',{name:'Open movies completed-download settings',exact:true}).click();await Promise.race([raceReadBegun,new Promise((_,reject)=>setTimeout(()=>reject(new Error('Race read gate not entered')),20000))]);releaseRaceWrite();await child.getByText('Write accepted; related settings or processing status readback incomplete. Check processing status.',{exact:true}).waitFor();releaseRaceRead();await activity.getByText('Settings navigation refused: resolve the unknown write outcome, then request navigation again.',{exact:true}).waitFor();assert.equal(await master.getByLabel('Completed-download media').inputValue(),'tv');await page.unroute(racePolicy);await page.unroute('**/api/v1/commands?*');await idle(activity);
 await child.getByRole('button',{name:'Check processing status',exact:true}).click();await child.getByText('Saved policy and related settings checked. Review before another action.',{exact:true}).waitFor();await idle(activity);await openHealth();await settings('movies');await openHealth();await current();
 assert.equal((await page.request.post(remote+'/fixture-mode?mode=3')).status(),204);
 await run('all');await until(()=>get('/api/v1/health'),snapshot=>snapshot.active_command?.status==='running','No running owned health probe');
 const pending=await run('all');assert.equal(pending.outcome,'pending');await idle(health);await health.getByText('Not yet verified on this page — pending, stale, failed, or outside this scope/page.',{exact:true}).first().waitFor();
 let cancels=0;page.on('request',request=>{if(request.method()==='POST'&&request.url().includes('/health/commands/')&&request.url().endsWith('/cancel'))cancels++;});
 acceptDialogs=false;await health.getByRole('button',{name:'Cancel entire active batch',exact:true}).click();assert.equal(cancels,0);acceptDialogs=true;
 let releaseCancel,cancelStarted;const cancelGate=new Promise(resolve=>releaseCancel=resolve),cancelBegun=new Promise(resolve=>cancelStarted=resolve);held.push(releaseCancel);
 await page.route('**/api/v1/health/commands/*/cancel',async route=>{const response=await route.fetch();cancelStarted();await cancelGate;await route.fulfill({response});});
 await health.getByRole('button',{name:'Cancel entire active batch',exact:true}).click();await Promise.race([cancelBegun,new Promise((_,reject)=>setTimeout(()=>reject(new Error('Cancel gate not entered')),20000))]);
 for(const button of await health.getByRole('button',{name:/Inspect (batch|active batch)/}).all())assert.equal(await button.isDisabled(),true,'Detail navigation must not race a cancel response');
 releaseCancel();await idle(health);await page.unroute('**/api/v1/health/commands/*/cancel');assert.equal(cancels,1);assert.equal((await get(`/api/v1/health/commands/${pending.active_command_id}`)).status,'cancelled');assert.equal((await page.request.post(remote+'/fixture-mode?mode=0')).status(),204);await current();await dismiss();await refresh();
 // Lost accepted admission response: readback only, no automatic POST retry or inferred token success.
 let admissionWrites=0;await page.route('**/api/v1/health/commands',async route=>{if(route.request().method()!=='POST')return route.continue();admissionWrites++;assert.equal((await route.fetch()).status(),202);await route.abort('failed');});
 await health.getByRole('button',{name:'Run all health checks',exact:true}).click();await health.getByText('Outcome unknown; inspect recorded work before requesting again. No automatic mutation retry is performed.',{exact:true}).waitFor();await page.unroute('**/api/v1/health/commands');await refresh();assert.equal(admissionWrites,1);assert.equal(await health.getByRole('button',{name:'Run all health checks',exact:true}).isDisabled(),true);await health.getByRole('button',{name:'I reviewed recorded work; allow a new request',exact:true}).click();
 // Changed status must be serialized in the first request, before binding effects.
 const filtered=page.waitForRequest(request=>request.url().includes('/health/commands?')&&new URL(request.url()).searchParams.get('status')==='failed');await health.getByLabel('Health command status').selectOption('failed');await filtered;await idle(health);await health.getByLabel('Health command status').selectOption('');await idle(health);
 if(process.env.UI_SCREENSHOT_DIR){await page.screenshot({path:process.env.UI_SCREENSHOT_DIR+'/health-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:process.env.UI_SCREENSHOT_DIR+'/health-mobile.png',fullPage:true});await page.setViewportSize({width:1280,height:720});}
 console.log('PASS actual API: both-domain observations/settings, equal true save, dirty/busy/unknown navigation, running/pending/cancel, lost admission');
 // Controlled response overlays: these establish rendering/race behavior only.
 await run('all');await current();await refresh();
 const base=await get('/api/v1/health');let overlay=structuredClone(base);const healthPattern='**/api/v1/health?*';
 await page.route(healthPattern,route=>route.fulfill({json:overlay}));
 overlay.lifecycle.epoch='00000000-0000-4000-8000-000000000001';await refresh();await health.getByText('Not yet verified on this page — pending, stale, failed, or outside this scope/page.',{exact:true}).waitFor();overlay=structuredClone(base);await refresh();await health.getByText('Requested generations observed in the current epoch.',{exact:true}).waitFor();await dismiss();
 overlay.summary={total:6,current:1,never_run:2,stale:3,failed:2,non_ok:2};overlay.total=6;overlay.active_command=null;overlay.lifecycle.schedule_error='health_invariant';overlay.lifecycle.grace_phase='pending';overlay.lifecycle.grace_due_at=1;
 overlay.checks=['never_run','pending','running','stale','failed','current'].map((evaluation,n)=>({...base.checks[0],identity:{scope:n%2?'tv':'movies',check_key:`render_${n}`},evaluation,checked_at:n<3?null:base.checks[0].checked_at,observed_generation:n<3?null:base.checks[0].observed_generation,last_error:n===4?'owned_failed_probe':null}));overlay.coverage.identities=overlay.checks.map(check=>check.identity);overlay.issues=[{...base.issues[0],identity:overlay.checks[4].identity,severity:'warning',reason:'retained',message:'<script>unsafe</script> retained warning',wiki_url:'javascript:alert(1)',compatibility_type:'fixture'}];
 await refresh();await health.getByText('Scheduler error: health_invariant',{exact:true}).waitFor();for(const evaluation of ['never_run','pending','running','stale','failed','current'])await health.getByRole('heading',{name:new RegExp(`— ${evaluation}$`)}).waitFor();assert.equal(await health.getByRole('link',{name:'Check help'}).count(),0);assert.equal(await health.getByText('No current issues in registered checks.',{exact:true}).count(),0);await health.getByText('warning: <script>unsafe</script> retained warning (retained)',{exact:true}).waitFor();
 // Empty page cannot hide nonzero scoped summary; zero system registry is never green.
 overlay.checks=[];overlay.issues=[];await refresh();await health.getByText('No checks on this page. Scoped summary above covers all registered checks.',{exact:true}).waitFor();assert.equal(await health.getByText('No current issues in registered checks.',{exact:true}).count(),0);
 overlay.summary={total:0,current:0,never_run:0,stale:0,failed:0,non_ok:0};overlay.total=0;overlay.coverage.identities=[];await health.getByLabel('Health scope').selectOption('system');await idle(health);await health.getByText('No registered checks in this scope.',{exact:true}).waitFor();assert.equal(await health.getByText('No current issues in registered checks.',{exact:true}).count(),0);
 await page.unroute(healthPattern);await health.getByLabel('Health scope').selectOption('all');await idle(health);
 // Failed GET retains content and labels it stale.
 await page.route(healthPattern,route=>route.fulfill({status:503,json:{error:{code:'owned',message:'Owned health GET failure'}}}));await refresh();await health.getByRole('alert').filter({hasText:'Health read failed: Owned health GET failure. Retained observations may be stale.'}).waitFor();assert.equal(await health.getByRole('region',{name:'Registered check coverage'}).count(),1);await page.unroute(healthPattern);
 // A delayed old scope response cannot replace the new selection, nor wedge the busy flag.
 let releaseHealth,healthStarted;const healthGate=new Promise(resolve=>releaseHealth=resolve),healthBegun=new Promise(resolve=>healthStarted=resolve);held.push(releaseHealth);let holdHealth=true;
 await page.route(healthPattern,async route=>{if(!holdHealth)return route.continue();holdHealth=false;const response=await route.fetch();healthStarted();await healthGate;await route.fulfill({response});});
 await health.getByRole('button',{name:'Refresh health',exact:true}).click();await Promise.race([healthBegun,new Promise((_,reject)=>setTimeout(()=>reject(new Error('Health gate not entered')),20000))]);await health.getByLabel('Health scope').selectOption('movies');await nav.getByRole('button',{name:'Library',exact:true}).click();releaseHealth();await page.waitForTimeout(300);assert.equal(await health.isVisible(),false);await openHealth();await idle(health);await health.getByRole('heading',{name:'movies coverage',exact:true}).waitFor();assert.equal(await health.getByRole('article',{name:'tv:completed_download_handling',exact:true}).count(),0);await page.unroute(healthPattern);
 // Hide panel after completed reads, then wait past one poll interval: no hidden polling.
 let reads=0;page.on('request',request=>{if(new URL(request.url()).pathname==='/api/v1/health')reads++;});await nav.getByRole('button',{name:'Library',exact:true}).click();await page.waitForTimeout(500);const hiddenReads=reads;await page.waitForTimeout(5500);assert.equal(reads,hiddenReads);await openHealth();assert.ok(reads>hiddenReads);
 // Global diagnostic discontinuity remains visible even after a later no-gap page.
 let gapResponse={oldest_retained_sequence:20,latest_sequence:21,next_cursor:20,gap:true,items:[{sequence:20,event_id:'owned-restored',epoch:base.lifecycle.epoch,command_id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',kind:'restored',in_grace:true,created_at:1,issue:{identity:{scope:'movies',check_key:'completed_download_handling'},severity:'warning',reason:'previous',message:'Previous disabled issue',wiki_url:'',compatibility_type:'fixture'}}]};
 await page.route('**/api/v1/health/transitions?*',route=>route.fulfill({json:gapResponse}));await refresh();await health.getByText('Retention gap observed: earlier transitions are unavailable.',{exact:true}).waitFor();await health.getByText(/restored — movies:completed_download_handling, warning: Previous disabled issue/).waitFor();gapResponse={...gapResponse,gap:false,items:[],next_cursor:21};await health.getByRole('button',{name:'Newer events',exact:true}).click();await idle(health);await health.getByText('Retention gap observed: earlier transitions are unavailable.',{exact:true}).waitFor();await page.unroute('**/api/v1/health/transitions?*');
 // Synthetic running-cancel response loss remains unresolved by a nonterminal read or a pruned ID.
 const recorded=(await get('/api/v1/health/commands')).items[0];const running={...recorded,status:'running',completed_at:null};
 const withRunning={...base,active_command:running};let detailGone=false,cancelAttempts=0;
 await page.route(healthPattern,route=>route.fulfill({json:withRunning}));
 await page.route(`**/api/v1/health/commands/${running.id}`,route=>detailGone?route.fulfill({status:404,json:{error:{code:'health_not_found',message:'Owned pruned detail'}}}):route.fulfill({json:running}));
 await page.route(`**/api/v1/health/commands/${running.id}/cancel`,async route=>{cancelAttempts++;await route.abort('failed');});
 await refresh();await health.getByRole('button',{name:'Cancel entire active batch',exact:true}).click();await health.getByText('Outcome unknown; inspect recorded work before requesting again. No automatic mutation retry is performed.',{exact:true}).waitFor();await idle(health);assert.equal(await health.getByRole('button',{name:/Run .* health checks/}).isDisabled(),true);assert.equal(cancelAttempts,1);
 detailGone=true;await refresh();await health.getByRole('alert').filter({hasText:'Batch unknown or pruned; cancellation is not confirmed.'}).waitFor();assert.equal(await health.getByRole('button',{name:/Run .* health checks/}).isDisabled(),true);assert.equal(cancelAttempts,1);
 await health.getByRole('button',{name:'I reviewed recorded work; allow a new request',exact:true}).click();await page.unroute(`**/api/v1/health/commands/${running.id}/cancel`);await page.unroute(`**/api/v1/health/commands/${running.id}`);await page.unroute(healthPattern);
 // Registry limit 128: sixteen rows per page, with all eight pages reachable and bounded.
 const checks=Array.from({length:128},(_,n)=>({...base.checks[0],identity:{scope:'tv',check_key:`bounded_${n}`}}));
 await page.route(healthPattern,route=>{const offset=Number(new URL(route.request().url()).searchParams.get('offset'));assert.ok(offset>=0&&offset<=127);return route.fulfill({json:{...base,total:128,offset,limit:16,active_command:null,checks:checks.slice(offset,offset+16),issues:[],coverage:{registered_only:true,identities:checks.map(check=>check.identity)},summary:{total:128,current:128,never_run:0,stale:0,failed:0,non_ok:0}}});});
 await health.getByLabel('Health scope').selectOption('all');await idle(health);await refresh();
 for(let n=0;n<8;n++){assert.equal(await health.getByRole('article').count(),16);await health.getByText(`Check offset ${n*16}; up to 16 per page.`,{exact:true}).waitFor();if(n<7){await health.getByRole('button',{name:'Next checks',exact:true}).click();await idle(health);}}
 assert.equal(await health.getByRole('button',{name:'Next checks',exact:true}).isDisabled(),true);await page.unroute(healthPattern);await health.getByLabel('Health scope').selectOption('tv');await idle(health);
 // Retained 128 terminal batches plus one active batch: final partial history page stays reachable.
 await page.route('**/api/v1/health/commands?*',route=>{const offset=Number(new URL(route.request().url()).searchParams.get('offset'));assert.ok(offset<=128);return route.fulfill({json:{total:129,offset,limit:20,items:Array.from({length:Math.min(20,129-offset)},(_,n)=>({...recorded,id:`00000000-0000-4000-8000-${String(n+offset).padStart(12,'0')}`}))}});});
 await refresh();for(let n=0;n<6;n++){await health.getByRole('button',{name:'Next batches',exact:true}).click();await idle(health);}assert.equal(await health.getByRole('button',{name:/Inspect batch /}).count(),9);assert.equal(await health.getByRole('button',{name:'Next batches',exact:true}).isDisabled(),true);await health.getByRole('button',{name:'Newest batches',exact:true}).click();await idle(health);await page.unroute('**/api/v1/health/commands?*');
 // Controlled document visibility event, independent of workspace visibility.
 await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});const documentHiddenReads=reads;await page.waitForTimeout(5500);assert.equal(reads,documentHiddenReads);await page.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));});await idle(health);assert.ok(reads>documentHiddenReads);
 console.log('PASS controlled overlays: unknown cancellation stays blocked for running/pruned readback,128-check/129-history boundaries,document visibility');
 assert.deepEqual(errors,[]);await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'Health should fit mobile viewport');
 console.log('PASS controlled overlays: six evaluation states, overlapping counters, unsafe links, empty pages/system, retained failures, stale response fencing, hidden polling, diagnostic gap; no page errors');
}catch(error){console.error('PAGESTATE', (await page.locator('body').innerText()).slice(0,10000));console.error('PAGEERRORS',errors);throw error;}finally{for(const release of held)release();await page.unrouteAll({behavior:'wait'});await browser.close();}
