// Real endpoints on an owned ephemeral fixture; held routes make write races deterministic.
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE||'/usr/lib/node_modules/playwright/index.mjs').href);
const origin=process.env.UI_URL,scratch=process.env.UI_SCRATCH;assert.ok(origin&&scratch);assert.equal(new URL(origin).hostname,'127.0.0.1');
const browser=await chromium.launch({headless:true});const page=await browser.newPage();page.setDefaultTimeout(15000);
const errors=[];page.on('pageerror',error=>errors.push(error.message));
const tags=page.getByRole('region',{name:'Tags settings',exact:true}),assign=page.getByRole('region',{name:'Library tags',exact:true}),nav=page.getByRole('navigation',{name:'Workspace',exact:true});
const root=d=>d==='tv'?'tv/series':'movies';
async function read(path){const response=await page.request.get(`${origin}/api/v1/${path}`);assert.equal(response.status(),200);return response.json();}
async function management(domain){await nav.getByRole('button',{name:'Tags',exact:true}).click();const button=tags.getByRole('button',{name:domain==='tv'?'TV':'Movies',exact:true});await page.waitForFunction(()=>!document.querySelector('section[aria-label="Tags settings"] input')?.disabled);if(await button.getAttribute('aria-pressed')!=='true')await button.click();await tags.getByRole('button',{name:'Create tag',exact:true}).waitFor();await page.waitForFunction(()=>{const el=document.querySelector('section[aria-label="Tags settings"] fieldset');return el&&!el.disabled;});}
async function create(label){await tags.getByLabel('Tag label',{exact:true}).fill(label);await tags.getByRole('button',{name:'Create tag',exact:true}).click();await tags.getByText('Tag saved.',{exact:true}).waitFor();}
async function library(domain){await nav.getByRole('button',{name:'Library',exact:true}).click();const button=page.getByRole('navigation',{name:'Library type'}).getByRole('button',{name:domain==='tv'?'TV':'Movies',exact:true});if(await button.getAttribute('aria-pressed')!=='true')await button.click();}
async function reloadAssignments(){await assign.getByRole('button',{name:'Reload tags and assignments',exact:true}).click();await page.waitForFunction(()=>{const f=document.querySelector('section[aria-label="Library tags"] form fieldset');return f&&!f.disabled;});}
async function apply(domain){const response=page.waitForResponse(r=>r.url().endsWith(`/${root(domain)}/editor`)&&r.request().method()==='PUT');await assign.getByRole('button',{name:'Apply tags',exact:true}).click();const result=await response;await assign.getByText(/Tags saved for/).waitFor();return result;}
try{
 await page.goto(origin);
 for(const domain of ['tv','movies']){
  await management(domain);await create('Primary');await create('PRIMARY');let catalog=await read(`${domain}/tags`);assert.equal(catalog.filter(tag=>tag.label==='primary').length,1);
  await create('temporary');await tags.getByRole('button',{name:'Rename temporary',exact:true}).click();await tags.getByLabel('Tag label').fill('secondary');await tags.getByRole('button',{name:'Save tag',exact:true}).click();await tags.getByText('Tag saved.',{exact:true}).waitFor();
  catalog=await read(`${domain}/tags`);const primary=catalog.find(t=>t.label==='primary'),secondary=catalog.find(t=>t.label==='secondary');assert.ok(primary&&secondary);
  // Create-time tags use the actual metadata lookup and settings writer.
  await library(domain);await page.getByRole('button',{name:domain==='tv'?'Add series':'Add movie',exact:true}).click();await page.getByLabel('Search catalogue').fill('Fixture');await page.getByRole('button',{name:'Search',exact:true}).click();await page.getByRole('button',{name:new RegExp(`Fixture ${domain==='tv'?'series':'movie'} .*`)}).click();await page.getByLabel('Existing library directory').fill(`${scratch}/${domain==='tv'?'tv':'movies'}`);
  const creation=page.getByRole('group',{name:'Tags for new library item'});await creation.getByRole('button',{name:'Load creation tags',exact:true}).click();await creation.getByLabel('primary',{exact:true}).check();
  const createPattern=`**/api/v1/${root(domain)}/lookup`;await page.route(createPattern,async route=>{if(route.request().method()==='POST'){await route.fetch();await route.abort('failed');}else await route.continue();});await page.getByRole('button',{name:'Add to library',exact:true}).click();await page.getByText('Add outcome unknown.',{exact:false}).waitFor();await nav.getByRole('button',{name:'Tags',exact:true}).click();assert.equal(await tags.getByRole('button',{name:'Create tag',exact:true}).isDisabled(),true);await library(domain);assert.equal(await page.getByRole('button',{name:'Add to library',exact:true}).isDisabled(),true);assert.equal(await creation.getByLabel('primary',{exact:true}).isChecked(),true);await page.unroute(createPattern);await page.getByRole('button',{name:'Check creation outcome',exact:true}).click();await page.getByRole('article').getByRole('heading',{name:`Fixture ${domain==='tv'?'series':'movie'}`,exact:true}).waitFor();
  const item=(await read(root(domain))).items.find(i=>i.title.startsWith('Fixture'));assert.deepEqual(item.tag_ids,[primary.id]);const settings=item.settings;
  const extraResponse=await page.request.post(`${origin}/api/v1/${root(domain)}/lookup`,{data:{[domain==='tv'?'tvdb_id':'tmdb_id']:202,path:`${scratch}/search-${domain}-202`,settings:{monitored:false}}});assert.equal(extraResponse.status(),201,await extraResponse.text());const extra=await extraResponse.json();
  await page.getByRole('button',{name:'Refresh library',exact:true}).click();await assign.getByLabel(`${extra.title} (${extra.id})`,{exact:true}).waitFor();await reloadAssignments();
  await assign.getByLabel(`${item.title} (${item.id})`,{exact:true}).check();await assign.getByLabel(`${extra.title} (${extra.id})`,{exact:true}).check();await assign.getByLabel('secondary',{exact:true}).check();assert.equal((await apply(domain)).status(),200);
  assert.deepEqual((await read(`${root(domain)}/${item.id}`)).tag_ids,[primary.id,secondary.id].sort((a,b)=>a-b));assert.deepEqual((await read(`${root(domain)}/${extra.id}`)).tag_ids,[secondary.id]);assert.deepEqual((await read(`${root(domain)}/${item.id}`)).settings,settings);assert.equal((await read(`${root(domain)}/${extra.id}`)).monitored,false);
  await management(domain);await tags.getByRole('button',{name:'Reload tags',exact:true}).click();await tags.getByRole('button',{name:'Usage of secondary',exact:true}).click();await tags.getByRole('heading',{name:'secondary: 2 library owners',exact:true}).waitFor();await tags.getByRole('button',{name:'Delete secondary',exact:true}).click();await tags.getByRole('button',{name:'Cancel tag deletion',exact:true}).click();assert.ok((await read(`${domain}/tags`)).some(t=>t.id===secondary.id));await tags.getByRole('button',{name:'Delete secondary',exact:true}).click();const rejected=page.waitForResponse(r=>r.url().endsWith(`/tags/${secondary.id}`)&&r.request().method()==='DELETE');await tags.getByRole('button',{name:'Confirm delete tag',exact:true}).click();assert.equal((await rejected).status(),409);
  await library(domain);assert.equal(await assign.getByRole('button',{name:'Apply tags',exact:true}).isDisabled(),true);await reloadAssignments();await assign.getByLabel('secondary',{exact:true}).check();await assign.getByLabel('Tag action').selectOption('remove');assert.equal((await apply(domain)).status(),200);assert.deepEqual((await read(`${root(domain)}/${item.id}`)).tag_ids,[primary.id]);
  // Hold an assignment across workspace navigation; management cannot race it.
  await assign.getByLabel('Tag action').selectOption('replace');await assign.getByLabel('secondary',{exact:true}).uncheck();let capture;const held=new Promise(resolve=>capture=resolve);const pattern=`**/api/v1/${root(domain)}/editor`;await page.route(pattern,route=>capture(route));await assign.getByRole('button',{name:'Apply tags',exact:true}).click();const heldRoute=await held;
  await nav.getByRole('button',{name:'Tags',exact:true}).click();assert.equal(await tags.getByRole('button',{name:'Create tag',exact:true}).isDisabled(),true);await nav.getByRole('button',{name:'Library',exact:true}).click();assert.equal(await assign.getByRole('button',{name:'Apply tags',exact:true}).isDisabled(),true);assert.equal(await assign.getByLabel('Tag action').inputValue(),'replace');
  await heldRoute.continue();await page.unroute(pattern);await assign.getByText('Tags saved for 2 library items.',{exact:true}).waitFor();assert.deepEqual((await read(`${root(domain)}/${item.id}`)).tag_ids,[]);assert.deepEqual((await read(`${root(domain)}/${extra.id}`)).tag_ids,[]);
  // A lost response must retain the draft and require explicit full assignment readback.
  await assign.getByLabel('primary',{exact:true}).check();await page.route(pattern,async route=>{await route.fetch();await route.abort('failed');});await assign.getByRole('button',{name:'Apply tags',exact:true}).click();await assign.getByText('Assignment outcome unknown.',{exact:false}).waitFor();await nav.getByRole('button',{name:'Tags',exact:true}).click();assert.equal(await tags.getByRole('button',{name:'Create tag',exact:true}).isDisabled(),true);await library(domain);assert.equal(await assign.getByLabel('primary',{exact:true}).isChecked(),true);assert.equal(await assign.getByRole('button',{name:'Apply tags',exact:true}).isDisabled(),true);await page.unroute(pattern);await reloadAssignments();assert.deepEqual((await read(`${root(domain)}/${item.id}`)).tag_ids,[primary.id]);
  await management(domain);await tags.getByRole('button',{name:'Delete secondary',exact:true}).click();await tags.getByRole('button',{name:'Confirm delete tag',exact:true}).click();await tags.getByText('Tag deleted.',{exact:true}).waitFor();assert.ok(!(await read(`${domain}/tags`)).some(t=>t.id===secondary.id));
  // Reverse guard: a lost catalog write blocks library assignment until catalog readback.
  const renamePattern=`**/api/v1/${domain}/tags/${primary.id}`;await tags.getByRole('button',{name:'Rename primary',exact:true}).click();await tags.getByLabel('Tag label').fill(`renamed-${domain}`);await page.route(renamePattern,async route=>{if(route.request().method()==='PUT'){await route.fetch();await route.abort('failed');}else await route.continue();});await tags.getByRole('button',{name:'Save tag',exact:true}).click();await tags.getByText('Write outcome unknown.',{exact:false}).waitFor();await library(domain);assert.equal(await assign.getByRole('button',{name:'Apply tags',exact:true}).isDisabled(),true);await nav.getByRole('button',{name:'Tags',exact:true}).click();assert.equal(await tags.getByLabel('Tag label').inputValue(),`renamed-${domain}`);assert.equal(await tags.getByRole('button',{name:'Save tag',exact:true}).isDisabled(),true);await page.unroute(renamePattern);await tags.getByRole('button',{name:'Reload tags',exact:true}).click();await tags.getByRole('button',{name:`Rename renamed-${domain}`,exact:true}).waitFor();await tags.getByRole('button',{name:'Cancel rename',exact:true}).click();
 }
 // Usage paging is backed by real owners, not a synthetic rendered response.
 for(const domain of ['tv','movies']){
  const tag=(await read(`${domain}/tags`)).find(t=>t.label===`renamed-${domain}`);
  for(let index=0;index<24;index++){const path=`${scratch}/tag-owner-${domain}-${index}`;await mkdir(path);const response=await page.request.post(`${origin}/api/v1/${root(domain)}`,{data:{title:`Tag owner ${domain} ${index}`,[domain==='tv'?'tvdb_id':'tmdb_id']:10000+index,path,settings:{tags:{mode:'replace',ids:[tag.id]}}}});assert.equal(response.status(),201,await response.text());}
  await management(domain);await tags.getByRole('button',{name:'Reload tags',exact:true}).click();await tags.getByRole('button',{name:`Usage of renamed-${domain}`,exact:true}).click();const usage=tags.getByRole('region',{name:'Tag usage'});await usage.getByRole('heading',{name:`renamed-${domain}: 26 library owners`,exact:true}).waitFor();assert.equal(await usage.getByRole('listitem').count(),25);await usage.getByRole('button',{name:'Next owners',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('section[aria-label="Tag usage"] li').length===1);assert.equal(await usage.getByRole('button',{name:'Next owners',exact:true}).isDisabled(),true);await usage.getByRole('button',{name:/Open (series|movie)/}).click();await page.getByRole('article').getByRole('heading',{name:`Tag owner ${domain} 23`,exact:true}).waitFor();
 }
 // A late TV catalog read cannot strand loading state or replace movie labels.
 await library('tv');let releaseRead;const heldRead=new Promise(resolve=>releaseRead=resolve);const readPattern='**/api/v1/tv/tags';await page.route(readPattern,route=>releaseRead(route));await assign.getByRole('button',{name:'Reload tags and assignments',exact:true}).click();const oldRead=await heldRead;await library('movies');await reloadAssignments();const oldResponse=page.waitForResponse(r=>r.url().endsWith('/tv/tags'));await oldRead.continue();await oldResponse;await page.unroute(readPattern);assert.equal(await assign.getByLabel('renamed-movies',{exact:true}).count(),1);assert.equal(await assign.getByLabel('renamed-tv',{exact:true}).count(),0);
 assert.ok((await read('tv/tags')).some(t=>t.label==='renamed-tv'));assert.ok((await read('movies/tags')).some(t=>t.label==='renamed-movies'));assert.deepEqual(errors,[]);console.log('Tags browser passed: both-domain CRUD, creation, atomic add/remove/empty replace, usage/delete protection, navigation and unknown-write guards.');
}finally{await browser.close();}
