<script lang="ts">
 import {onMount,untrack} from 'svelte';
 import type {MediaDomain,ReleaseProfileCatalog,ReleaseProfile,Provider,Tag,ApiPage} from './api.generated';
 import type {Result,SettingsWriteState} from './api';
 import {listReleaseProfiles,getReleaseProfileSchema,createReleaseProfile,updateReleaseProfile,deleteReleaseProfile,listTags,listProviders,getProvider} from './api';
 import {fromInput,toInput,validate,eligible,referenceKey,moveTerm,type Draft,type Input} from './release-profile-draft';
 let {tagVersions,relatedWrites,onwrite,onchange,request=null}:{tagVersions:Record<MediaDomain,number>;relatedWrites:Record<MediaDomain,SettingsWriteState>;onwrite:(d:MediaDomain,s:SettingsWriteState)=>void;onchange:(d:MediaDomain)=>void;request?:{domain:MediaDomain;id?:number;nonce:number}|null}=$props();
 let domain=$state<MediaDomain>('tv'),catalog=$state<ReleaseProfileCatalog|null>(null),schema=$state<Input|null>(null),tags=$state<Tag[]>([]),providers=$state<ApiPage<Provider>|null>(null),known=$state<Record<string,Provider>>({});
 let draft=$state<Draft|null>(null),id=$state<number|null>(null),baseline=$state(0),dirty=$state(false),stale=$state(false),uncertain=$state(false),busy=$state(false),loading=$state(false),referenceLoading=$state(false),referenceError=$state(false),error=$state(''),notice=$state(''),deleting=$state<ReleaseProfile|null>(null),replacement=$state<string|null>(null),tagVersion=$state(-1);
 let epoch=0,alive=true,initialized=false,seenRequest=0;
 const labelsStale=$derived(catalog!==null&&tagVersion!==tagVersions[domain]);
 const blocked=$derived(busy||loading||referenceLoading||uncertain||labelsStale||relatedWrites[domain]!=='idle');
 $effect(()=>{const version=tagVersions[domain];untrack(()=>{if(catalog&&version!==tagVersion){deleting=null;if(draft)stale=true;}});});
 $effect(()=>{if(relatedWrites[domain]!=='idle')deleting=null;});
 onMount(()=>()=>{alive=false;++epoch;});
 function discard(){return !dirty||window.confirm('Discard unsaved release profile changes?');}
 function changed(){dirty=true;deleting=null;notice='';}
 async function load(reset=false){
  if(busy||loading||relatedWrites[domain]!=='idle')return false;
  const token=++epoch,scope=domain,version=tagVersions[scope];referenceLoading=false;loading=true;deleting=null;error='';replacement=null;
  const [all,defaults,labels,choices]=await Promise.all([listReleaseProfiles(scope),getReleaseProfileSchema(scope),listTags(scope),listProviders(0)]);
  if(!alive||token!==epoch)return false;loading=false;
  if(!all.ok||!defaults.ok||!labels.ok||!choices.ok){error=[all,defaults,labels,choices].filter(r=>!r.ok).map(r=>r.ok?'':r.error).join(' ');return false;}
  if(version!==tagVersions[scope]||relatedWrites[scope]!=='idle'){error='Tags changed while loading. Reload before editing.';return false;}
  catalog=all.data;schema=defaults.data;tags=labels.data;providers=choices.data;known=Object.fromEntries(choices.data.items.map(p=>[p.id,p]));tagVersion=version;
  if(reset){draft=null;id=null;dirty=false;stale=false;}else if(draft)stale=true;
  uncertain=false;onwrite(scope,'idle');notice='Catalog loaded. Reopen a profile to use its current revision.';return true;
 }
 async function open(scope:MediaDomain,profileId?:number){
  if(busy||uncertain||relatedWrites[domain]!=='idle'||relatedWrites[scope]!=='idle'){error='Finish or reconcile the current settings write first.';return;}
  if(!discard())return;++epoch;loading=false;referenceLoading=false;domain=scope;catalog=null;schema=null;providers=null;tags=[];known={};draft=null;id=null;dirty=false;stale=false;referenceError=false;notice='';deleting=null;
  const token=epoch;if(await load(true)&&alive&&epoch===token+1&&domain===scope&&profileId!==undefined)await edit(profileId);
 }
 $effect(()=>{const target=request;untrack(()=>{if(!initialized){initialized=true;seenRequest=target?.nonce??0;void open(target?.domain??'tv',target?.id);}else if(target&&target.nonce!==seenRequest){seenRequest=target.nonce;void open(target.domain,target.id);}});});
 async function edit(profileId:number|null){
  if(blocked||!catalog||!schema||!discard())return;
  const value=profileId===null?schema:catalog.profiles.find(p=>p.id===profileId);if(!value){error='Profile no longer exists. Reload the catalog.';return;}
  draft=fromInput(domain,value);id=profileId;baseline=catalog.revision;dirty=false;stale=false;deleting=null;replacement=null;error='';notice='';referenceError=false;
  const ids=draft.value.indexers.flatMap(r=>r.kind==='provider'?[r.id]:[]);if(!ids.length)return;
  const token=++epoch,scope=domain;referenceLoading=true;const resolved:Record<string,Provider>={};
  // Selected references are bounded by the native profile limit; fetch at most four at once.
  for(let start=0;start<ids.length;start+=4){const results=await Promise.all(ids.slice(start,start+4).map(getProvider));if(!alive||token!==epoch)return;for(const result of results){if(!result.ok||!eligible(result.data,scope)){referenceError=true;error='A selected indexer is unavailable. Reload or explicitly remove/replace its reference.';}else resolved[result.data.id]=result.data;}}
  known={...known,...resolved};referenceLoading=false;
 }
 async function providerPage(offset:number){if(blocked)return;const token=++epoch;referenceLoading=true;error='';const result=await listProviders(offset);if(!alive||token!==epoch)return;referenceLoading=false;if(!result.ok){error=result.error;return;}providers=result.data;known={...known,...Object.fromEntries(result.data.items.map(p=>[p.id,p]))};}
 function removeReference(key:string){if(!draft)return;const next=draft.value.indexers.filter(r=>referenceKey(r)!==key);if(!next.length&&!window.confirm('Remove the last indexer restriction? This profile will apply to all indexers.'))return;draft.value.indexers=next;replacement=null;referenceError=next.some(r=>r.kind==='provider'&&(!known[r.id]||!eligible(known[r.id],domain)));changed();}
 function chooseProvider(p:Provider){if(!draft||!eligible(p,domain))return;const refs=draft.value.indexers;if(refs.some(r=>r.kind==='provider'&&r.id===p.id)){error='This indexer is already selected.';return;}if(replacement){draft.value.indexers=refs.map(r=>referenceKey(r)===replacement?{kind:'provider',id:p.id}:r);replacement=null;}else if(domain==='movies'&&refs.length){error='Remove or replace the selected movie indexer first.';return;}else draft.value.indexers=[...refs,{kind:'provider',id:p.id}];referenceError=draft.value.indexers.some(r=>r.kind==='provider'&&(!known[r.id]||!eligible(known[r.id],domain)));changed();}
 async function mutate(action:()=>Promise<Result<ReleaseProfileCatalog>>,message:string){if(blocked)return;const scope=domain,token=++epoch;busy=true;deleting=null;error='';notice='';onwrite(scope,'busy');const result=await action();if(!alive||token!==epoch)return;busy=false;if(!result.ok){error=result.code?`${result.error} (${result.code})`:result.error;uncertain=result.status===undefined||result.status>=500;stale=result.status===409||uncertain;onwrite(scope,uncertain?'uncertain':'idle');if(uncertain)onchange(scope);return;}catalog=result.data;draft=null;id=null;dirty=false;stale=false;replacement=null;onwrite(scope,'idle');onchange(scope);notice=message;}
 async function save(){if(blocked||stale||referenceError||!draft)return;error=validate(draft,tags);if(error)return;const body={revision:baseline,profile:toInput(draft)};await mutate(()=>id===null?createReleaseProfile(domain,body):updateReleaseProfile(domain,id!,body),'Release profile saved.');}
 async function remove(){if(blocked||!catalog||!deleting)return;const target=deleting.id,revision=catalog.revision;await mutate(()=>deleteReleaseProfile(domain,target,revision),'Release profile deleted.');}
 const label=(p:ReleaseProfile)=>p.name===null?`Unnamed profile ${p.id}`:p.name===''?`Empty-name profile ${p.id}`:p.name;
</script>
<section aria-label="Release profiles"><h2>Release profiles</h2>
<nav aria-label="Release profile media"><button disabled={busy||uncertain||relatedWrites[domain]!=='idle'} aria-pressed={domain==='tv'} onclick={()=>open('tv')}>TV</button><button disabled={busy||uncertain||relatedWrites[domain]!=='idle'} aria-pressed={domain==='movies'} onclick={()=>open('movies')}>Movies</button></nav>
<p>Every applicable enabled profile applies. Required terms are alternatives within a profile; all applicable profiles must pass. Any ignored match rejects. Empty include tags or indexers means all; excluded TV tags veto inclusion.</p>
{#if loading}<p role="status">Loading release profiles…</p>{/if}{#if busy}<p role="status">Saving release profile…</p>{/if}{#if error}<p role="alert">{error}</p>{/if}{#if notice}<p role="status">{notice}</p>{/if}
{#if uncertain}<p role="alert">Write outcome unknown. Keep this draft and reload the catalog before another write. A create may already exist: select its saved row instead of creating it again.</p>{/if}
{#if stale||labelsStale}<p role="alert">Draft is stale. Reload, review and explicitly reopen before saving.</p>{/if}
{#if relatedWrites[domain]!=='idle'}<p role="status">Finish or reconcile the tag write before changing release profiles.</p>{/if}
<button disabled={busy||loading||relatedWrites[domain]!=='idle'} onclick={()=>load()}>Reload release catalog</button><button disabled={blocked||!catalog} onclick={()=>edit(null)}>New release profile</button>
{#if catalog}<ul>{#each catalog.profiles as p(p.id)}<li><strong>{label(p)}</strong> · {p.enabled?'Enabled':'Disabled'} · {p.required.length} required / {p.ignored.length} ignored terms <button disabled={blocked} onclick={()=>edit(p.id)}>Edit release profile {p.id}</button><button disabled={blocked} onclick={()=>{if(discard())deleting=p;}}>Delete release profile {p.id}</button></li>{:else}<li>No release profiles in this media type.</li>{/each}</ul>{/if}
{#if draft}<form onsubmit={event=>{event.preventDefault();void save();}} oninput={changed}><fieldset disabled={blocked||stale}><legend>{id===null?'New release profile':`Release profile ${id}`}</legend>
<label><input type="checkbox" bind:checked={draft.unnamed}/>Unnamed (null name)</label><label>Profile name<input disabled={draft.unnamed} bind:value={draft.name}/></label>
<label><input type="checkbox" bind:checked={draft.value.enabled} disabled={draft.value.indexers.some(r=>r.kind==='unresolved_source')}/>Enabled</label>
{#each ['required','ignored'] as raw}{@const kind=raw as 'required'|'ignored'}<fieldset><legend>{kind==='required'?'Required terms':'Ignored terms'}</legend>{#each draft.value[kind] as term,index}<div><label>{kind} term {index+1}<textarea aria-label={`${kind} term ${index+1}`} bind:value={draft.value[kind][index]}></textarea></label><button type="button" disabled={index===0} onclick={()=>{draft!.value[kind]=moveTerm(draft!.value[kind],index,-1);changed();}}>Move {kind} term {index+1} up</button><button type="button" disabled={index===draft.value[kind].length-1} onclick={()=>{draft!.value[kind]=moveTerm(draft!.value[kind],index,1);changed();}}>Move {kind} term {index+1} down</button><button type="button" onclick={()=>{draft!.value[kind]=draft!.value[kind].filter((_,i)=>i!==index);changed();}}>Remove {kind} term {index+1}</button></div>{/each}<button type="button" disabled={draft.value[kind].length>=200} onclick={()=>{draft!.value[kind]=[...draft!.value[kind],''];changed();}}>Add {kind} term</button></fieldset>{/each}
<details><summary>Term and regex help</summary><p>Literal substrings ignore case. A pair of slashes within a line selects a regex, including when surrounded by text. Use /pattern/flags; regex is case-sensitive unless i is supplied. Modifiers: i, m, s, x, n. Terms retain whitespace, duplicates and order. Up to 200 terms per list and 2048 UTF-8 bytes per term; the catalog also has total work limits.</p><p>Save validates with the native matcher. Balancing groups, class subtraction, duplicate/numbered captures, explicit Unicode properties, ambiguous octal and other unsupported engine constructs are rejected. Arbitrary .NET/culture equivalence is not claimed.</p></details>
<fieldset><legend>Include tags (empty means all)</legend>{#each tags as tag(tag.id)}<label><input type="checkbox" bind:group={draft.value.tag_ids} value={tag.id}/>{tag.label}</label>{:else}<p>No tags available.</p>{/each}</fieldset>
{#if 'excluded_tag_ids' in draft.value}<fieldset><legend>Excluded tags</legend>{#each tags as tag(tag.id)}<label><input type="checkbox" bind:group={draft.value.excluded_tag_ids} value={tag.id}/>{tag.label}</label>{/each}</fieldset><label><input type="checkbox" bind:checked={draft.value.air_date_restriction}/>Restrict by air date</label><label>Air-date grace days<input inputmode="numeric" bind:value={draft.grace}/></label><p>The release publication time is compared with episode air dates and the maximum applicable grace period.</p><label><input type="checkbox" bind:checked={draft.value.allow_season_pack_without_all_episodes_aired}/>Allow season pack without all episodes aired</label>{/if}
<fieldset><legend>Indexer references</legend>{#each draft.value.indexers as ref(referenceKey(ref))}<div>{#if ref.kind==='provider'}<span>{known[ref.id]?.name??`Unavailable indexer ${ref.id}`} {known[ref.id]&&!known[ref.id].enabled?'(disabled)':''}</span>{:else}<p>Unavailable source indexer: {ref.application} #{ref.source_id}. Keep disabled until explicitly resolved or removed.</p><details><summary>Source identity</summary><code>{ref.fingerprint}</code></details>{/if}<button type="button" onclick={()=>removeReference(referenceKey(ref))}>Remove indexer {ref.kind==='provider'?ref.id:ref.source_id}</button><button type="button" onclick={()=>replacement=referenceKey(ref)}>Replace indexer {ref.kind==='provider'?ref.id:ref.source_id}</button></div>{:else}<p>All indexers.</p>{/each}
{#if replacement}<p role="status">Choose a native indexer below to replace this reference.</p><button type="button" onclick={()=>replacement=null}>Cancel replacement</button>{/if}
{#if providers}<p>Indexer choices from provider records {providers.offset+1}–{providers.offset+providers.items.length} of {providers.total}.</p>{#each providers.items.filter(p=>eligible(p,domain)) as p(p.id)}<button type="button" disabled={draft.value.indexers.some(r=>r.kind==='provider'&&r.id===p.id)} onclick={()=>chooseProvider(p)}>Choose indexer {p.name}{p.enabled?'':' (disabled)'}</button>{:else}<p>No scoped indexers on this page.</p>{/each}<button type="button" disabled={providers.offset===0} onclick={()=>providerPage(Math.max(0,providers!.offset-25))}>Previous indexers</button><button type="button" disabled={providers.offset+providers.limit>=providers.total} onclick={()=>providerPage(providers!.offset+providers!.limit)}>Next indexers</button>{/if}
</fieldset><button disabled={referenceError}>Save release profile</button><button type="button" onclick={()=>{if(discard()){draft=null;id=null;dirty=false;replacement=null;}}}>Cancel release edit</button>
</fieldset></form>{/if}
{#if referenceLoading}<p role="status">Loading indexer references…</p>{/if}
{#if deleting}<div role="group" aria-label="Confirm release profile deletion"><p>Delete “{label(deleting)}”? Its restrictions will no longer apply.</p><button disabled={blocked} onclick={remove}>Confirm delete release profile</button><button disabled={busy} onclick={()=>deleting=null}>Cancel release deletion</button></div>{/if}
</section>
